Fix for PyBabel Compatibility with Python 3.12 and Third-Party Extractors
python-babel/babel pull request #1093
Opened 2024-07-03 09:33 UTC by podgorniy94

PyBabel currently fails to work with Python 3.12 when using third-party extractors. Specifically, the extraction method for Jinja2 templates throws a ValueError:

```
[python: **.py]
[jinja2: templates/**.html]
ValueError: Unknown extraction method 'jinja2'
```

This issue does not occur with Python 3.11, where the same setup functions correctly.

Issue: https://github.com/python-babel/babel/issues/861

2024-07-03 09:35 UTC, akx commented
I don't think all of our currently supported platforms have `importlib.metadata`, so this will likely fail CI, but we'll see...

2024-07-03 09:39 UTC, j123b567 commented
@akx you are right, it should try `pkg_resources` first and if it is not there, then try `importlib.metadata` and if it is not there, then do the fallback to predefined list

2024-07-03 09:44 UTC, akx requested changes
As discussed, this needs a fallback for environments where `importlib.metadata.entry_points()` is not available.

2024-07-08 13:34 UTC, podgorniy94 commented
Another fallback was needed, this time for `importlib.metadata`, specifically for `entry_points()`.

```
Error message:
AttributeError: 'str' object has no attribute 'group'
```

According to the documentation:

> _Compatibility_
> The "selectable" entry points were introduced in importlib_metadata 3.6 and Python 3.10. Prior to those changes, entry_points accepted no parameters and always returned a dictionary of entry points, keyed by group. With importlib_metadata 5.0 and Python 3.12, entry_points always returns an EntryPoints object. See backports.entry_points_selectable for compatibility options.

2024-07-18 12:28 UTC, akx commented
@podgorniy94 I wasn't sure you were doing that, so please just see #1102 instead – the commit has you as a co-author :)

2024-07-25 09:51 UTC, closed without merging