Implementation of msgcat and msgmerge utilities from GNU gettext
python-babel/babel pull request #1161
Opened 2024-12-09 19:14 UTC by soft-suroleb

### Implementation of some features for msgcat and msgmerge to work with a compendium in PyBabel

#### pybabel concat

- Allows concatenating multiple .po files into one.
- In case of translation conflicts, the translation from the first file is taken, as if the use-first option is set to true. Flags, locations, and other information in messages are combined.
- Implemented options:
  - output-file
  - less-than
  - more-than
  - unique
  - use-first
  - no-location
  - width
  - no-wrap
  - sort-output
  - sort-by-file

#### pybabel merge

- Enables merging files using a compendium for translation memory.
- The compendium can be used in two modes:
  - Default mode: Translations from the compendium are taken if absent in the output file.
  - Compendium overwrite mode: With the compendium-overwrite option, translations in the compendium are considered primary and overwrite those in the output file. If a translation is taken from the compendium, a comment is added specifying the source.
- Implemented options:
  - input-files
  - compendium
  - compendium-overwrite
  - no-compendium-comment
  - update
  - output-file
  - backup
  - suffix
  - no-fuzzy-matching
  - no-location
  - width
  - no-wrap
  - sort-output
  - sort-by-file

2025-02-28 13:17 UTC, soft-suroleb commented
Hi guys! I see you marked pr but still haven't left any comments. Will it be reviewed?

2025-03-17 14:40 UTC, akx requested changes
Thank you! Some initial comments within.

2025-03-17 14:40 UTC, akx commented on babel/messages/frontend.py
> +        # the first translation is always used temporarily
What does this comment mean?

2025-03-23 15:49 UTC, soft-suroleb commented on babel/messages/frontend.py
> +                            'If input file is -, standard input is read.'),
Removed as unused option

2025-03-23 15:52 UTC, soft-suroleb commented on babel/messages/frontend.py
> +        # the first translation is always used temporarily
When one message has different translations in different po-files, gnu gettext adds a note that there is a conflict/ I didn't implement this logic at first, but then i made a commit with conflict support, so i removed the comment

2025-03-23 15:54 UTC, soft-suroleb commented on babel/messages/frontend.py
> +            raise OptionError('you must specify the output file')
Do you want the result to be output to stdout or what? It's just that each command in frontend has a similar exception for the output_file

2025-03-23 15:56 UTC, soft-suroleb commented on babel/messages/frontend.py
> +            self.less_than = 2
Not quite so. More_than and less_than are like bounds. Unique means less_than=2 but boolean

2025-03-23 16:02 UTC, soft-suroleb commented on tests/messages/test_frontend.py
> +class ConcatanationCatalogTestCase(unittest.TestCase):
Is a new file really needed here? The file is test_frontend.py and all other tests for commands are there and it's logical that they will be there too, no?

2025-03-23 16:05 UTC, soft-suroleb commented
Made support for conflicting messages from different po-files during concatenation. If one message has different translations in different files, then the corresponding strings marked with a comment about conflict

2025-04-22 12:17 UTC, akx requested changes
Another round of comments :)

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +            for message in template:
This should probably also filter out messages with a nullish `id`.

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +            raise OptionError('must be two po files')
That would be useful information here in the error message too.

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +        ('input-files', None, 'def.po (obsolete translations) ref.pot (actual template)'),
```suggestion
        ('input-files', None, 'exactly two input files: def.po (obsolete translations); ref.pot (current template)'),
```

I assume "actual" means "current" here (common [false friend](https://en.wikipedia.org/wiki/False_friend)) :)

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +        for file_path in compendium:
Even if the CLI argument is in the singular, it would be nicer to read here in the plural.

Also, this clearly returns things in the plural:

```suggestion
    def _get_messages_from_compendiums(self, compendium_paths):
        if not compendium_paths:
            return
        for file_path in compendium_paths:
```

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +                        current.auto_comments.append(compendium_path)
This could be unnested, and `get_messages_from_compendiums` could early-return if the passed argument is falsy.

```suggestion
        for message, compendium_path in self._get_message_from_compendium(self.compendium):
            current = catalog[message.id]
            if message.id in catalog and (not current.string or current.fuzzy or self.compendium_overwrite):
                if self.compendium_overwrite and not current.fuzzy and current.string:
                    catalog.obsolete[message.id] = current.clone()

                current.string = message.string
                if current.fuzzy:
                    current.flags.remove('fuzzy')

                if not self.no_compendium_comment:
                    current.auto_comments.append(compendium_path)
```

2025-04-22 12:17 UTC, akx commented on docs/cmdline.rst
> +The `concat` command merges multiple PO files into a single one. If a message has
```suggestion
The `concat` command merges multiple PO files into one. If a message has
```

2025-04-22 12:17 UTC, akx commented on docs/cmdline.rst
> +and the message itself is marked with a `fuzzy` flag::
Is the `::` on purpose here?

2025-04-22 12:17 UTC, akx commented on docs/cmdline.rst
> +    $ pybabel concat --help
```suggestion
    $ pybabel merge --help
```

2025-04-22 12:17 UTC, akx commented on docs/concat_merge_usage.rst
> +Usage scenarios
I think these could be in the `cmdline.rst` file – they'd probably be easier to find there.

2025-04-22 12:17 UTC, akx commented on docs/cmdline.rst
> +The ``input-files`` option includes def.po, a file with obsolete translations, and ref.pot,
```suggestion
The ``input-files`` option accepts exactly two arguments: a file with obsolete translations, and
```

2025-04-22 12:17 UTC, akx commented on docs/cmdline.rst
> +By default, a standard suffix ``~`` is appended to the backup file's name,
```suggestion
The ``backup`` option is used to create a backup copy of the def.po file, which contains
obsolete translations. The ``suffix`` option allows you to specify a custom suffix for the backup file (defaulting to ``~``).
```

2025-04-22 12:17 UTC, akx commented on babel/messages/frontend.py
> +        'merge': 'combines two Uniforum-style PO files into one',
I still have no idea what an Uniforum-style PO file is; do we not support whatever is a non-Uniforum-style PO file?

2025-04-22 12:17 UTC, akx commented on babel/messages/pofile.py
> +        comment = f"#-#-#-#-#  {file} ({project} {version})  #-#-#-#-#"
Is this standard notation, or are we introducing a Babel-specific comment extension? If the latter, I'd rather not...

2025-04-27 12:01 UTC, soft-suroleb commented on babel/messages/pofile.py
> +        comment = f"#-#-#-#-#  {file} ({project} {version})  #-#-#-#-#"
This is the notation used in gnu gettext
/

2025-06-13 09:30 UTC, soft-suroleb commented
Guys? Will there be another round? :)

2025-06-24 12:18 UTC, akx commented
@soft-suroleb Sorry, I was honeymooning in Japan for the last 3 weeks 😄 

There's still a bunch of unresolved comments from me from the last round of review, I think?

2025-07-06 13:40 UTC, soft-suroleb commented
Oh, my congrats :) Yeah, but there is question for you in the unresolved comment

2025-09-04 09:29 UTC, soft-suroleb commented
Guys?

2025-10-08 10:03 UTC, akx commented
> Oh, my congrats :) Yeah, but there is question for you in the unresolved comment

Looking at this again... Sorry, which comment? There's a bunch of comments unresolved 😅

2025-11-09 16:21 UTC, soft-suroleb commented
https://github.com/python-babel/babel/pull/1161#discussion_r1998899769

This comment. And why bunch of comments? I think only that, all others were being resolved

2025-11-12 12:31 UTC, akx commented
Things like https://github.com/python-babel/babel/pull/1161/files/dd44348272edb1d8bd86818f16ea54809cfd0851#diff-9b4dc8cb664f244c13aebdf018a3748731477a5bb7903a9677326c7ebc177f7b et al – GitHub can be confusing with the "hidden conversations" marker sometimes hiding unresolved comments
<img width="836" height="90" alt="Screenshot 2025-11-12 at 14 30 24" src="https://github.com/user-attachments/assets/0b94fe81-2e22-49da-92b2-269d9a09572f" />
but every outstanding comment should be available on the Files page.

2025-11-12 12:32 UTC, akx commented on tests/messages/test_frontend.py
> +class ConcatanationCatalogTestCase(unittest.TestCase):
Well, TBH `test_frontend.py` could also be split into more files – smaller files tend to be easier to read and review.

2026-04-07 19:40 UTC, FrBrGeorge commented
I have to ask — how is it going? I'm waiting for this feature since it was implemented in 2024… Can I help to move it further somehow?

2026-04-08 16:58 UTC, soft-suroleb commented
@akx @FrBrGeorge 
All review comments have been addressed:

- Removed fuzzy flag mutation from `add_conflict` — the caller now sets it explicitly
- Refactored `ConcatenateCatalog`: fixed help texts, output to stdout when no `--output-file` is given, added mutual exclusivity of `--unique` with `--less-than`/`--more-than`, replaced nested dict with `Counter` + `defaultdict`, renamed `_prepare` → `_collect_message_info`
- Fixed `MergeCatalog`: corrected description, fixed typo in `--update` help, added missing help texts, fixed `multiple_value_options` tuple (missing trailing comma), improved error message, renamed and refactored `_get_messages_from_compendiums` with early return and walrus operator
- Fixed `cmdline.rst`: corrected heading levels, typos, `pybabel concat` → `pybabel merge` in the merge section, updated help text examples

Also expanded the test suite with additional cases: stdout output, `--unique` mutual exclusivity, `--use-first` behaviour, and plural message handling.

2026-04-10 06:31 UTC, akx requested changes
Thanks for addressing the previous comments!

Another round within - something I'd be extra careful about is those new APIs you're adding to `Catalog`; public APIs are hard to change neatly afterwards, so they should be designed with precision...

2026-04-10 06:31 UTC, akx commented on babel/messages/catalog.py
> +        key = message.id
Should this use `self._key_for` like for keying `self._messages` above? IOW, should keying take message context into account?

2026-04-10 06:31 UTC, akx commented on babel/messages/frontend.py
> +        message_counts: Counter = Counter()
```suggestion
        message_counts = Counter()
```
The type hint doesn't add extra information :)

2026-04-10 06:31 UTC, akx commented on babel/messages/frontend.py
> +        message_strings: dict[object, set] = defaultdict(set)
Could we have a tighter key type than `object`? Could the type of the set also be determined? (I'm looking at line 974, where it's hard for me to figure out what the actual set value type is.)

2026-04-10 06:31 UTC, akx commented on babel/messages/frontend.py
> +            return
Unnecessary, unless you imply for `compendium_paths` to be None sometimes, which sounds unlikely?
```suggestion
```

2026-04-10 06:31 UTC, akx commented on babel/messages/pofile.py
> +                if line[1:].startswith('~'):
Please see https://github.com/python-babel/babel/commit/d7a7589a6cee3aa4c68de60f4d69a9cdad50a7ff - we're avoiding `.startswith` on purpose.

2026-04-10 06:31 UTC, akx commented on babel/messages/pofile.py
> +                    self._invalid_pofile(line, lineno, 'cannot parse po file with conflicts')
Should this be a warning rather than a hard error? Rather, how has Babel parsed files with these conflict markers in the past?

2026-04-10 06:31 UTC, akx commented on babel/messages/catalog.py
> +        return self._conflicts.get(id, [])
These new public APIs should be designed with care (e.g. should these actually take message instances?) and have docstrings.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +
I'd appreciate it if this test file was written in Pytest style (see #1240, #1241 for the conversion that occurred recently) from the get-go?

Could I also ask for it to be split into `test_concat` and `test_merge`, like `test_compile` and `test_extract` already are?

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +class TestConcatanateCatalog:
Typo in suite name.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +            pofile.write_po(file, catalog)
It looks like this wouldn't need to mess with `data_dir` at all, but just work in a Pytest `tmp_path`?

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +                    os.unlink(file)
This would become unnecessary using `tmp_path`.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        self.cmd.initialize_options()
`concat_cmd` could be a Pytest fixture.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        self.output_file = f'{i18n_dir}/msgcat.po'
These could be `pathlib.Path`s.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        assert expected_content == actual_content
I wonder if it's worth it to check this bit-by-bit exactness? For a reader of the test, or the code, it's hard to see what the logic is - a test that would explain what's different when `use_first` is enabled (and test for that result) would probably be better...

(You could consider this comment repeated for all of the `assert expected_content == actual_content` snapshot tests.)

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        assert expected_content == actual_content
Should we test that `read_po()` fails for this file? (Shouldn't it, given the new error there?)

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +            self.cmd.run()
[`contextlib.redirect_stdout`](https://docs.python.org/3.14/library/contextlib.html#contextlib.redirect_stdout) in general, but pytest has a [`capsys` fixture](https://docs.pytest.org/en/stable/how-to/capture-stdout-stderr.html) fir this exact purpose.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +            self.cmd.run()
As above, re stdout capturing

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        self.compendium = f'{i18n_dir}/compenidum.po'
Typo: compenidum

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        self.cmd.initialize_options()
This could become a `merge_cmd` fixture (see `extract_cmd`)

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +    def test_compenidum(self):
Typo: compenidum

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +    def test_compenidum_overwrite(self):
Typo: compenidum

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""msgid "word1"
```suggestion
        expected_content = self._get_expected("""msgid "word1"
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""#: simple.py:1
```suggestion
        expected_content = self._get_expected("""#: simple.py:1
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""#: simple.py:1
```suggestion
        expected_content = self._get_expected("""#: simple.py:1
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""#: simple.py:1
```suggestion
        expected_content = self._get_expected("""#: simple.py:1
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""#: hard.py:100 simple.py:100
```suggestion
        expected_content = self._get_expected("""#: hard.py:100 simple.py:100
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""msgid "word1"
```suggestion
        expected_content = self._get_expected("""msgid "word1"
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""msgid "word1"
```suggestion
        expected_content = self._get_expected("""msgid "word1"
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        expected_content = self._get_expected(fr"""msgid "word1"
```suggestion
        expected_content = self._get_expected("""msgid "word1"
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        assert os.path.exists(self.temp_def + '~')
```suggestion
```
Unnecessary assertion, the next line will fail with FileNotFoundError if it's not there.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +        assert os.path.exists(self.temp_def + '.bac')
Ditto, unnecessary assertion.
```suggestion
```

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +                os.unlink(compendium2)
Try-finally would be unnecessary with tmp_path fixture.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +                os.unlink(compendium_with_word3)
Ditto, try-finally unnecessary with tmp_path.

2026-04-10 06:31 UTC, akx commented on tests/messages/frontend/test_concat_merge.py
> +                os.unlink(extra_def)
Ditto, try-finally unnecessary with tmp_path.

2026-04-10 12:40 UTC, soft-suroleb commented on babel/messages/pofile.py
> +                    self._invalid_pofile(line, lineno, 'cannot parse po file with conflicts')
_invalid_pofile is already a warning by default — it only raises when abort_invalid=True is explicitly passed to read_po().

Previously, #-#-#-#-# lines had no special handling: they silently became user comments, and the conflicted msgstr was parsed as regular text, producing a malformed catalog with no diagnostic. The current behavior is strictly better.

2026-04-10 12:50 UTC, soft-suroleb commented on tests/messages/frontend/test_concat_merge.py
> +            self.cmd.run()
capsys doesn't work here because the code writes to sys.stdout.buffer (binary stream), not sys.stdout — so monkeypatch is used instead.

2026-04-10 12:57 UTC, soft-suroleb commented
@akx @FrBrGeorge

Addressed all review comments from the latest round:
**catalog.py** — `add_conflict` now uses `_key_for(id, context)` so messages with `msgctxt` are keyed correctly; added docstrings to `add_conflict` and `get_conflicts`
**frontend.py** — tightened type hints (`Counter[_MessageID]`, `dict[_MessageID, ...]`); removed redundant early-return guard in `_get_messages_from_compendiums`; initialized `self.compendium` as `[]`
**pofile.py** — replaced `.startswith()` calls with slice comparisons per the codebase convention
**tests** — split `test_concat_merge.py` into `test_concat.py` and `test_merge.py`; converted to pytest style with `tmp_path`, `monkeypatch`, `pathlib.Path`; replaced snapshot assertions with targeted checks; fixed `compenidum` typo; added `test_conflicted_po_raises_on_read`
Left two comments for discussion:
- **pofile conflict handling** — `_invalid_pofile` is already a warning by default (only raises with `abort_invalid=True`), which is strictly better than the old behavior of silently parsing conflict markers as user comments
- **stdout capture** — `capsys` doesn't work here since the code writes to `sys.stdout.buffer` (binary), so `monkeypatch` is used instead

2026-08-13 15:50 UTC, akx approved these changes
Thank you for putting up with all of the review comments!

I'll merge this - finally! - and follow up with a couple of small things in a follow-up PR soon.

2026-08-13 15:53 UTC, merged