Run locale identifiers through `os.path.basename()`
python-babel/babel pull request #782
Opened 2021-04-28 07:34 UTC by akx

2021-04-28 08:14 UTC, mitsuhiko requested changes
This is kinda okay but there is a potential concern. Since certain names are reserved on windows you could cause a DOS by for instance trying to load `aux.dat` or similar files. To make this safer this should likely assert it's not in the list of reserved file names.

`basename` itself might be okay. While there are some scary inputs like `..` loading the join of dirname name `...dat` is still okay.

2021-04-28 08:54 UTC, akx commented
@mitsuhiko Good call on the special filenames, I had forgotten those are still a thing on Windows. I added another commit that refactors the previous single call to `basename` to a function that resolves locale identifiers into full paths, taking them into account.

2021-04-28 09:24 UTC, mitsuhiko approved these changes

2021-04-28 14:29 UTC, merged

2021-05-06 15:11 UTC, StayPirate commented
CVE-2021-20095 has been assigned to this

2021-05-06 15:13 UTC, StayPirate commented
CVE-2021-20095 has been assigned to this.

2021-06-16 17:21 UTC, carnil commented
CVE-2021-20095 appers to have been rejected again "This candidate was withdrawn by its CNA" according to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-20095

2021-06-22 12:02 UTC, StayPirate commented
Anybody knows something more about the rejection from Tenable? I can't find any useful information on their blog.

2021-10-21 07:46 UTC, Beuc commented
CVE-2021-42771 now describes this issue.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42771