Add flag to ignore POT-Creation-Date for updates
python-babel/babel pull request #999
Opened 2023-04-11 16:47 UTC by joeportela

Adding a flag to ignore changes to POT-Creation-Date when performing updates or checks. 
I use a CI check that ensures my .po files are updated before merging, but there is always a diff on POT-Creation-Date.

Related to https://github.com/python-babel/babel/issues/725 - but solving (my) problem via update instead of extract.

2023-06-23 17:52 UTC, joeportela commented
Ping @akx 
Any interest in this PR?

2023-06-27 18:52 UTC, akx requested changes
Thank you for the contribution! As mentioned inside, I think it could be more intuitive for the kwarg to be positive (and default to True).

2023-06-27 18:52 UTC, akx commented on babel/messages/catalog.py
> +        ignore_pot_creation_date: bool = False,
I think

```suggestion
        update_creation_date: bool = True,
```

would be more intuitive? 

The command line parameter could be left `--ignore-pot-creation-date` though.

2023-07-05 19:17 UTC, joeportela commented
> Thank you for the contribution! As mentioned inside, I think it could be more intuitive for the kwarg to be positive (and default to True).

My pleasure, thanks for taking a look! Just updated per your suggestion.

2023-07-27 11:24 UTC, akx approved these changes
LGTM, sorry for the delay!

2023-07-27 11:24 UTC, merged